env = Environment(tools = ['default','textfile'])
env.Append(CCFLAGS=['-g','-Wall'],
           LINKFLAGS=['-g'],
           LIBS=['m'])
print "platform = ", env['PLATFORM']

env['VERSION'] = "0.1.5"

env.Substfile("version.h",
              "version.h.in",
              SUBST_DICT = {'@VERSION@':env['VERSION']})

env.ParseConfig('pkg-config --libs --cflags gtk+-2.0')

bin = env.Program('gxgraph',
                  ['gxgraph.c',
                   'gtk_painter.c',
                   'ps_painter.c',
                   'svg_painter.c',
                   'moving_ants.c',
                   'gxgraph_hardcopy.c',
                   'gxgraph_about.c',
                   'parser.c'])

env.Alias("install",
          [env.Install('/usr/local/bin',
                       bin),
           ])
